version: "3"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_HOST=postgres
      - DB_PASSWORD=abc123
      - API_HOST=api
      - PYTHONDONTWRITEBYTECODE=1
      - FLASK_APP=allocation/entrypoints/flask_app.py
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=1
    volumes:
      - ./src:/src
      - ./tests:/tests
    ports:
      - "5005:80"
    depends_on:
      postgres:
        condition: service_healthy
    entrypoint:
      - flask
      - run
      - --host=0.0.0.0
      - --port=80    

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=allocation
      - POSTGRES_PASSWORD=abc123
    ports:
      - "54321:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "allocation"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
